version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install hatch
      - hatch env create

sphinx:
  configuration: docs/conf.py
  # TODO: uncomment once docs build without autosummary warnings
  # fail_on_warning: true
