version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with=docs

sphinx:
  configuration: docs/conf.py
  # TODO: uncomment once docs build without autosummary warnings
  # fail_on_warning: true
